version: "3"
services:
  db:
    image: mariadb:10.1.21
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php:
    image: php:7.1.2-fpm-alpine
    volumes:
      - "./html:/var/www/html"
    links:
      - db

  admin:
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - db
    environment:
      - PMA_ABSOLUTE_URI=/phpmyadmin

  web:
    image: nginx:1.11.10-alpine
    ports:
      - "8080:80"
    volumes:
      - "./conf/nginx:/etc/nginx/conf.d/"
      - "./html:/var/www/html"
    links:
      - php
      - admin
