# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alegent <alegent@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/12/15 09:58:29 by alegent           #+#    #+#              #
#    Updated: 2016/12/16 12:33:25 by alegent          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=root

php:
  image: php:fpm-alpine
  volumes:
    - "./html:/var/www/html"
  links:
    - db

admin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    - PMA_ABSOLUTE_URI=/phpmyadmin

web:
  image: nginx:alpine
  ports:
    - "8080:80"
  volumes:
    - "./conf/nginx:/etc/nginx/conf.d/"
    - "./html:/var/www/html"
  links:
    - php
    - admin
