version: "3"
services: 
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./html:/var/www/html"
  
  angular:
    build: angular
    volumes:
      - "./angular:/usr/src/app"
      - "./html:/var/www/html"