mongo:
  image: mongo:3.4.2
  command: mongod --auth
  volumes:
    - "./database:/data/db"

web:
  image: nginx:alpine
  ports:
    - "8080:80"
  links:
    - app
  volumes:
    - "./conf/nginx:/etc/nginx/conf.d"
