mongo:
  image: mongo
  command: mongod --auth
  volumes:
    - "./database:/data/db"

app:
  build: app
  volumes:
    - "./scripts:/scripts"
  links:
    - mongo

web:
  image: nginx:alpine
  ports:
    - "8080:80"
  links:
    - app
  volumes:
    - "./conf/nginx:/etc/nginx/conf.d"
